export default function ExportPDF({ weather, city }) {
  async function handleExport() {
    const { default: html2canvas } = await import("html2canvas");
    const el = document.querySelector("main");
    if (!el) return;

    const canvas = await html2canvas(el, { useCORS: true, scale: 2 });
    const imgData = canvas.toDataURL("image/png");

    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <html>
        <head>
          <title>Weather Report - ${city || "WeatherScope"}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
            img { width: 100%; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }
            .header { text-align: center; margin-bottom: 30px; }
            .header h1 { margin: 0; font-size: 24px; }
            .header p { color: #666; margin-top: 4px; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #999; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Weather Report${city ? ` — ${city}` : ""}</h1>
            <p>Generated by WeatherScope — ${new Date().toLocaleDateString()}</p>
          </div>
          <img src="${imgData}" alt="Weather snapshot" />
          <div class="footer">WeatherScope — weatherscope.app</div>
          <script>window.onload = function() { window.print(); };</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  }

  if (!weather) return null;

  return (
    <button
      onClick={handleExport}
      aria-label="Export weather report as PDF"
      className="bg-gray-800 dark:bg-slate-700 hover:opacity-90 text-white px-3 py-2 rounded-lg text-sm transition-opacity"
    >
      Export PDF
    </button>
  );
}
